### ISSUE TITLE
`proof-pile-2` may not be completely uploaded

### ISSUE THREAD

**Issue by ZubinGou** [zhangir-azerbayev/math-lm#103]
As mentioned in https://huggingface.co/datasets/EleutherAI/proof-pile-2/discussions/6, the following files are empty:

size | file
-- | --
13 | algebraic-stack/train/github-coq-train-0001.jsonl.zst
13 | algebraic-stack/train/github-coq-train-0002.jsonl.zst
13 | algebraic-stack/train/github-MATLAB-train-0001.jsonl.zst
13 | algebraic-stack/train/github-MATLAB-train-0002.jsonl.zst
13 | algebraic-stack/train/github-MATLAB-train-0003.jsonl.zst

**Comment by zhangir-azerbayev** [comment]
Discussion [here](https://huggingface.co/datasets/EleutherAI/proof-pile-2/discussions/6)
